### ISSUE TITLE
Create a README.md file.

### ISSUE THREAD

**Issue by dofywofy** [strygwyr69/Leetcode-java-solutions#1]
need help with creating a README.md file

**Comment by lorenzovngl** [comment]
Tell me everything

**Comment by nettle790** [comment]
kindly elaborate on the nature of the help you require for creating a readme.md file.

**Comment by dofywofy** [comment]
I apologize for the late reply. I would like a simple README.md file for Leetcode solutions which when clicked on a certain number (say 1 which is the Two Sum problem) would open that particular java file.

**Comment by nettle790** [comment]
sorry I am not well versed in java.may not be able to help with that.

**Comment by lorenzovngl** [comment]
@strygwyr69 do you want something like this below?

# LeetCode Java Solutions

1. [AddToArrayForm.java](https://github.com/strygwyr69/Leetcode-java-solutions/blob/main/AddToArrayForm.java)
2. [BuildArray.java](https://github.com/strygwyr69/Leetcode-java-solutions/blob/main/BuildArray.java)
3. [CheckIfPangram.java](https://github.com/strygwyr69/Leetcode-java-solutions/blob/main/CheckIfPangram.java)

and so on...

**Comment by dofywofy** [comment]
@nettle790 no problem!
@lorenzovngl yes I would very much love that.

**Comment by lorenzovngl** [comment]
Good! I'm starting working on it.

**Comment by dofywofy** [comment]
Thank you for your help @lorenzovngl !
